#!/usr/bin/env node
/**
 * Writes src/version.ts from package.json so `getContext().version` reports
 * the real package version.  A runtime `import pkg from '../package.json'`
 * would break the `files` / `exports` layout, so the value is baked into a
 * tracked source file instead.
 *
 * Runs from two places:
 *   - core's `prebuild` hook, so every `pnpm build` (including the one
 *     `prepublishOnly` triggers) regenerates it before compiling;
 *   - the root `version-packages` script, so the changesets "Version
 *     Packages" commit — locally or from the release workflow — includes the
 *     bumped file rather than leaving a stale one on main.
 *
 * The file is tracked in git on purpose: JSR publishes from `src/` and
 * honours .gitignore, and the react/vue test configs and the playground alias
 * `@byrding/core` straight to `src/`, so it must exist on a fresh checkout.
 *
 * Idempotent: only writes when the content would change, so a clean tree
 * stays clean after `pnpm build`.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), '..')
const { version } = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8'))
const target = join(pkgDir, 'src', 'version.ts')

const content =
  `// Generated by scripts/generate-version.mjs from package.json — do not edit.\n` +
  `// Regenerated by \`pnpm build\` (prebuild) and \`pnpm version-packages\`.\n` +
  `export const VERSION = '${version}'\n`

if (existsSync(target) && readFileSync(target, 'utf8') === content) {
  process.exit(0)
}

writeFileSync(target, content)
console.log(`[byrding] wrote packages/core/src/version.ts → ${version}`)
